# Basic workflow to test out STG-Q

name: CI

on: push

jobs:
  STGQ-tests:
    runs-on: [self-hosted, linux]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout STG-Q
        uses: actions/checkout@v2

      # Cleanup umbrella
      - name: Cleanup
        run: |
          . set_env_vars
          scripts/distclean.sh
          
      # Re-install STG
      - name: Install STGQ
        run: |
          . set_env_vars
          scripts/install_stgq.sh
          
      # Run STG-Q tests
      - name: Run STG-Q tests
        run: |
          . set_env_vars
          scripts/run_tests.sh
